# Generated by Django 5.1 on 2024-08-18 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QRCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_data', models.CharField(max_length=255)),
                ('scanned_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
